-- RESEARCH THE SQL KEYWORDS
-- WHAT IS THE GENERAL FORMAT FOR A SQL QUERY
-- WHAT IS A GROUP BY?


--  PLEASE USE THE FOLLOWING TABLE FOR THE BELOW EXERCISE:  SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CALL_CENTER
-- RETURN THE NUMBER OF DISTINCT CC_HOURS CATEGORIES FROM
-- RETURN THE NUMBER OF EMPLOYEES WHO WORK IN THE CALL CENTER TABLES
-- RETURN THE UNIQUE NUMBER OF EMPLOYEES IN THE CALL CENTER TABLES
-- RETURN THE NUMBER OF ROWS IN THE DATA SET
-- USING THE CUSTOMER DATA TABLE
-- RETURN THE NUMBER OF ROWS IN THE CUSTOMER TABLE 
-- HOW MANY CUSTOMERS DO YOU HAVE WHERE THEIR BIRTH COUNTRY IS CUBA?
--  CAN YOU GREAT A SUMMARY OF THE NUMBER OF THE NUMBER OF CUSTOMERS BY THEIR BIRTH COUNTRIES?
--  CAN YOU RENAME THE COUNT(*) COLUMN TO STATE THE NUMBER_OF_DISTINCT_CUSTOMERS_BY_COUNTRY
--  CAN YOU THEN ORDER THIS IN ASCENDING ORDER?
-- USING THE INVENTORY AND ITEM TABLES 
-- CAN YOU LINK INVENTORY TO ITEMS?
-- IF SO HOW, WHAT WOULD BE THE JOIN AND WHY
-- WHAT ARE THE NUMBER OF INPUT ROWS, WHAT ARE THE OUTPUT ROWS AFTER THE JOIN
-- WHAT WOULD HAPPEN IF YOU WERE TO HAVE MULTIPLE PRODUCTS WITH THE SAME ITEM_SK 
-- HOW MANY PRODUCT ITEMS HAVE THE MIN PRICE?
-- FIND THE PRODUCTS WHICH HAVE THE MIN PRICE AND THE LOWEST WHOLESALE PRICE


-- WHAT IS AN ALIAS TABLE?
-- WHAT FUNCTIONS IN PYTHON ARE SIMILAR TO THOSE IN SQL? CAN YOU EXPLAIN THE SIMILARITIES AND PROVIDE EXAMPLES?

-- WHAT OTHER SUMMARY STATISTICS CAN YOU DO IN SQL? 
-- CAN YOU CREATE SOME INSIGHTS FROM THE 